### ISSUE TITLE
`Can't create device` on windows

### ISSUE THREAD

**Issue by xiaoniu-578fa6bff964d005** [cobrce/interception_py#1]
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    c = interception()
  File "E:\temp\program\interception.py", line 28, in __init__
    raise e
  File "E:\temp\program\interception.py", line 22, in __init__
    interception.is_keyboard(i))
  File "E:\temp\program\interception.py", line 114, in __init__
    raise Exception("Can't create device")
Exception: Can't create device
```

**Comment by cobrce** [comment]
You should install the driver, download [interception release](https://github.com/oblitum/Interception/releases) and run "command line installer\command line installer.exe /install" with administrative privileges
