### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by mrtmy1** [cobrce/interception_py#4]
Hi, Thank you very much for the code.  when i run the example i get an error. I'm using python 2.7. I installed interception exe.  I would be glad if you help.

```
Traceback (most recent call last):
  File "C:\Documents and Settings\Administrator\Desktop\interception_py-master\_example_.py", line 1, in <module>
    from interception import  *
  File "C:\Documents and Settings\Administrator\Desktop\interception_py-master\interception.py", line 3, in <module>
    from consts import *
  File "C:\Documents and Settings\Administrator\Desktop\interception_py-master\consts.py", line 1, in <module>
    from enum import Enum
ImportError: No module named enum
```

**Comment by cobrce** [comment]
The enum module isn't built-in in Python 2.7, according to [stackoverflow](https://stackoverflow.com/a/40655587) you can install it with `pip install --upgrade pip enum34`, but still the project wasn't tested with python2.7 (I definitely should do something about that) and it may break somewhere else
